### ISSUE TITLE
Feature request: Clicking on a style a second time removes it from the prompt

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#10]
When clicking on a style, it adds it to the prompt. Clicking again adds it again, and so on. Clicking the style a second time should remove the wording from the prompt, which is the standard behavior of clicking an extra networks card in auto1111.

**Comment by javsezlol1** [comment]
ill see if i can get this to work.

**Comment by javsezlol1** [comment]
added

**Comment by ManOrMonster** [comment]
Great implementation. Love the new changes!
