### ISSUE TITLE
Bug: Apostrophe in prompt breaks the style

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#13]
Having an apostrophe in the prompt in the JSON will make it so the stylez card does not input the prompt or allow editing. An apostophe in "name" or "preview" works fine.

For instance, this prompt will not work:
```
{
    "name": "Terry O'Neill",
    "description": "British photographer, known for documenting the fashions, styles, and celebrities of the 1960s.",
    "preview": "Terry O'Neill.jpg",
    "prompt": "by Terry O'Neill",
    "negative": ""
}
```

But make this one change (remove the apostrophe in "prompt" value) and it works: ` "prompt": "by Terry ONeill",`

Also, I recommend adding Terry O'Neill as an artist. His prompt can make quite an impact on a photo.

**Comment by javsezlol1** [comment]
fixed and added Terry O'Neill
