### ISSUE TITLE
Updates keep reverting config.json

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#17]
When this updates, config.json changes "autoconvert" to "true" which converts all my styles again. I think this is happening due to all the branch renaming or creation or whatever has been going on the last couple of weeks.

It also deletes my favorites.

I don't want to autoconvert again, it errors out and then I have to update the config again and restart the UI. And of course I don't want my favorites gone.

I'm once again requesting that autoconvert be made into an optional button or something so this stops firing whenever a new update is made. It really shouldn't be in a config file. It should be something people can run at will.

And no one should ever lose their favorites.

Also, any changes made to existing stylez get overwritten. My Terry O'Neill style has a custom image which keeps getting overwritten.

**Comment by javsezlol1** [comment]
Sorry this shouldn't be happening I keep adding the configs file to the
ignore list and it keeps committing it! Sorry for the inconvenience, I may
make the config file generate from code if this keeps happening the only
thing that should change is the updated files not the config file or as
suggested by the one of the automatic devs is move the options to
shared.opts

**Comment by javsezlol1** [comment]
Fixed it. Creates the config file instead of downloading it shouldn't have any issue now, sorry about that

**Comment by javsezlol1** [comment]
It looks like there's no way for get hub to not overwrite the images.. Gitignore doesn't work the way I thought it did which explains alot. It looks like the only way is to make a separate repo containing all the styles and have sylez download that repo which suck because I can expand on it without doing some weird work around.....

**Comment by ManOrMonster** [comment]
Good to know. Thanks for the fix
