### ISSUE TITLE
Stylez window does not open

### ISSUE THREAD

**Issue by jrhyme** [javsezlol1/Stylez#20]
Hello. Yesterday I got acquainted with this plugin for the first time, installed it according to the instructions, both from the link and from the list of applications, but when I click on the palette icon, nothing happens. Automatiс is the latest version, I didn’t install third-party themes, I tested it on different browsers, it doesn’t work..Doesn't write anything in the console, doesn't show any errors.

os win 11.

**Comment by javsezlol1** [comment]
hmm if the button is there it should appear are you double clicking the palette icon ?

**Comment by javsezlol1** [comment]
also could you send me a list of  your installed extensions as well as your browser console log. in chrome > right click > inspect > console tab

**Comment by javsezlol1** [comment]
> I had same problem, until i disable all extensions of browser and SD, and then started enabling one by one. In my case problem was in mov2mov (https://github.com/Scholar01/sd-webui-mov2mov). After I disabled it, Stylez is working with all other extensions.

thanks im looking into this i cant see exactly whats causing it as im getting zero errors browser and cmd console

**Comment by javsezlol1** [comment]
Looks like its due to the movie2movie extension pulling in and reseting stylez, this will happen with any extension that is tabbed and uses img2img scripts. I'm proberly going to have to re write the extension to be a main menu tab and and reposition after the fact to get around this so bare with me I'm super busy as of late.

**Comment by javsezlol1** [comment]
> ## ![Снимок экрана 2023-11-08 105934](https://user-images.githubusercontent.com/25270760/281311566-53e078cf-6fe6-4baa-8425-4db9f1b44922.png)
> ![Снимок экрана 2023-11-08 105954](https://user-images.githubusercontent.com/25270760/281311587-197ef250-8a67-4a17-b156-5473cef5b429.png) ![Снимок экрана 2023-11-08 110659](https://user-images.githubusercontent.com/25270760/281311595-2981c5d2-ba46-425c-b35d-804c12ab821a.png) I am not a developer, and it probably far away of true, but i think it has depending that Stylez use floating window. It overlap (i am not sure if this is correct word) image generation area, in Lobe-theme it is more visible (screen with pink buttons), but similar even without Lobe, i tried it on differend displays , it looks the same. If conflict with mov2mov and similar extentions is impposible to fix by more or less easy way, maybe there is a reason to move Stilez in scripts? There is already (on the last screenshot) in scripts , but does nothing, just like trying to extend a spoiler like x/y/z plot or sd upscale. In any way for me is ok like Stylez is working now, i tried few similar extentions and Stilez it much more close what it want. So thank you for your work.

yes its this issue is because its floating and after my script is rearranged mov2mov is resetting it, i intend to keep it floating so im going to re work it ignore the fact that its in scripts it doesnt do anything. i will be trying to fix this soon , i have an idea of what to do just been busy

**Comment by javsezlol1** [comment]
hey guys just to let you know its fixed youu can leave mov2mov active now

**Comment by DemonAlone** [comment]
> hey guys just to let you know its fixed youu can leave mov2mov active now

Yes, i works for me now.
