### ISSUE TITLE
translate artists and styles

### ISSUE THREAD

**Issue by rexcnxie** [javsezlol1/Stylez#21]
How about adding a translation function, like a json file, where you can translate all the artists and styles into different languages, and then the interface will show up in that language automatically?

**Comment by javsezlol1** [comment]
do you mean a translation for the UI or for the actual styles themselves

**Comment by rexcnxie** [comment]
I mean the artists and styles, because sometimes I only know the artist's name in my native language, and I don't know their English name, so it's hard to search for them. It would be great if the UI could also translate into different languages.

**Comment by javsezlol1** [comment]
Hmmm imgoogle translate wouldn't work or chatgpt?

**Comment by rexcnxie** [comment]
Google Translate or ChatGPT can work, but the translation provided within the Stylez extensions is more straightforward and clear in comparison. The in-built translation is easily comprehensible.

**Comment by javsezlol1** [comment]
im not sure how this would be possible to be honest ?. Making translation would be a massive job, unless i used some existing lama model or something and even then there no guarantee of the translation being correct.
