### ISSUE TITLE
Many warnings in the console when starting the forge

### ISSUE THREAD

**Issue by Bigbigliar** [javsezlol1/Stylez#27]
this is what I get on startup, is there anything I can fix so that this doesn't happen and everything works?

S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:353: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  category_dropdown = gr.Dropdown(label="Category", choices=generate_styles_and_tags[1], value="All", lines=1, elem_id="style_Catagory", elem_classes="dropdown styles_dropdown",scale=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:354: GradioDeprecationWarning: unexpected argument for Button: label
  refresh_button = gr.Button(refresh_symbol, label="Refresh", elem_id="style_refresh", elem_classes="tool", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:354: GradioDeprecationWarning: unexpected argument for Button: lines
  refresh_button = gr.Button(refresh_symbol, label="Refresh", elem_id="style_refresh", elem_classes="tool", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:362: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  nsfwlvl = gr.Dropdown(label="NSFW:", choices=["None", "Soft", "Mature", "X"], value="None", lines=1, elem_id="civit_nsfwfilter", elem_classes="dropdown styles_dropdown",scale=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:363: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  sortcivit  = gr.Dropdown(label="Sort:", choices=["Most Reactions", "Most Comments", "Newest"], value="Most Reactions", lines=1, elem_id="civit_sortfilter", elem_classes="dropdown styles_dropdown",scale=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:364: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  periodcivit  = gr.Dropdown(label="Period:", choices=["AllTime", "Year", "Month", "Week", "Day"], value="AllTime", lines=1, elem_id="civit_periodfilter", elem_classes="dropdown styles_dropdown",scale=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:368: GradioDeprecationWarning: unexpected argument for Button: label
  civitAI_refresh = gr.Button(refresh_symbol, label="Refresh", elem_id="style_refresh", elem_classes="tool", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:368: GradioDeprecationWarning: unexpected argument for Button: lines
  civitAI_refresh = gr.Button(refresh_symbol, label="Refresh", elem_id="style_refresh", elem_classes="tool", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:395: GradioDeprecationWarning: unexpected argument for Checkbox: lines
  gr.Checkbox(value=True,label="Apply/Remove Prompt", elem_id="styles_apply_prompt", elem_classes="styles_checkbox checkbox", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:396: GradioDeprecationWarning: unexpected argument for Checkbox: lines
  gr.Checkbox(value=True,label="Apply/Remove Negative", elem_id="styles_apply_neg", elem_classes="styles_checkbox checkbox", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:397: GradioDeprecationWarning: unexpected argument for Checkbox: lines
  gr.Checkbox(value=True,label="Hover Over Preview", elem_id="HoverOverStyle_preview", elem_classes="styles_checkbox checkbox", lines=1)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:398: GradioDeprecationWarning: unexpected argument for Checkbox: lines
  oldstylesCB = gr.Checkbox(value=hideoldstyles,label="Hide Styles Bar", elem_id="hide_default_styles", elem_classes="styles_checkbox checkbox", lines=1,interactive=True)
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:415: GradioDeprecationWarning: unexpected argument for Button: label
  style_save_btn = gr.Button(save_symbol,label="Save Style", lines=1,elem_classes="tool", elem_id="style_save_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:415: GradioDeprecationWarning: unexpected argument for Button: lines
  style_save_btn = gr.Button(save_symbol,label="Save Style", lines=1,elem_classes="tool", elem_id="style_save_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:416: GradioDeprecationWarning: unexpected argument for Button: label
  style_clear_btn = gr.Button(clear_symbol,label="Clear", lines=1,elem_classes="tool" ,elem_id="style_clear_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:416: GradioDeprecationWarning: unexpected argument for Button: lines
  style_clear_btn = gr.Button(clear_symbol,label="Clear", lines=1,elem_classes="tool" ,elem_id="style_clear_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:417: GradioDeprecationWarning: unexpected argument for Button: label
  style_delete_btn = gr.Button(delete_style,label="Delete Style", lines=1,elem_classes="tool", elem_id="style_delete_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:417: GradioDeprecationWarning: unexpected argument for Button: lines
  style_delete_btn = gr.Button(delete_style,label="Delete Style", lines=1,elem_classes="tool", elem_id="style_delete_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:421: GradioDeprecationWarning: unexpected argument for Button: label
  style_grab_current_btn = gr.Button("Grab Prompts",label="Grab Current", lines=1, elem_id="style_grab_current_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:421: GradioDeprecationWarning: unexpected argument for Button: lines
  style_grab_current_btn = gr.Button("Grab Prompts",label="Grab Current", lines=1, elem_id="style_grab_current_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:422: GradioDeprecationWarning: unexpected argument for Button: label
  style_lastgen_btn =gr.Button("Grab Last Generated Image",label="Save Style", lines=1,elem_id="style_lastgen_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:422: GradioDeprecationWarning: unexpected argument for Button: lines
  style_lastgen_btn =gr.Button("Grab Last Generated Image",label="Save Style", lines=1,elem_id="style_lastgen_btn")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:429: GradioDeprecationWarning: unexpected argument for Button: label
  style_savefolder_refrsh_btn = gr.Button(refresh_symbol, label="Refresh", lines=1,elem_classes="tool")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:429: GradioDeprecationWarning: unexpected argument for Button: lines
  style_savefolder_refrsh_btn = gr.Button(refresh_symbol, label="Refresh", lines=1,elem_classes="tool")
S:\Program Files\ForgeWebUI\webui\extensions\Stylez\scripts\Stylez.py:430: GradioDeprecationWarning: unexpected argument for Dropdown: lines
  style_savefolder_txt = gr.Dropdown(label="Save Folder (Type To Create A New Folder):", value="Styles", lines=1, choices=generate_styles_and_tags[2], elem_id="style_savefolder_txt", elem_classes="dropdown",allow_custom_value=True)

**Comment by javsezlol1** [comment]
Never tried this with forge sorry i made this for automatic1111
