### ISSUE TITLE
old style.csv with weird style names fails to convert

### ISSUE THREAD

**Issue by erajomppa** [javsezlol1/Stylez#3]
Hi, I was just able to get the extension working, but I'd like to let you know of a problem I had.
After first starting the UI with the extension installed, the extension tries to convert the old style.csv styles into json files.
In my case there were dummy styles, which were named such as:

___*NEGATIVE PROMPTS ONLY___

and styles with "/" character in them:

Digital/Oil painting

These gave errors and the extension did not work.
As expected, files with those names could not be created.
After removing the extension I renamed the styles in the styles.csv without special characters and everything seems to work just fine.
My old styles were converted successfully now,
But in case someone else decides to name their styles in the styles.csv with special characters, maybe a check should be in place to alter them before converting them into a file with that name?

![image](https://github.com/javsezlol1/Stylez/assets/7688333/f85b1476-25a5-47d1-af03-0e2bdf64ea35)

**Comment by javsezlol1** [comment]
thanks ill look into this !

**Comment by javsezlol1** [comment]
just to let you know i have fixed this now but haved pushed the update out just yet making some visual adjustmensts too so ill leave this issue open for now

**Comment by javsezlol1** [comment]
this has been fixed in the latest update
