### ISSUE TITLE
Bug: Saved styles with newline (\n) do not work.

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#6]
I often use new lines in my prompts for readability. In the JSON that was saved, these show up as "\n".

When trying to recall such a prompt from the saved style, it would not fill in the prompts. Additionally, it would not allow editing the style with the edit button. I had to manually remove the "\n" instances form the raw JSON, then was able to recall the prompt and edit it in the UI.

**Comment by javsezlol1** [comment]
okay thanks will look iointo this

**Comment by javsezlol1** [comment]
should be fixed  :) just update

**Comment by ManOrMonster** [comment]
I don't see any new commits. Auto1111 doesn't either.

**Comment by javsezlol1** [comment]
strange ? they are updated
