### ISSUE TITLE
Feature request: Crop thumbnails instead of resizing them

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#8]
Thumbnails that aren't square are resized to be square, which distorts the image. I suggest one of three options:

1. Crop the image instead of resizing
2. FIt the image into a square and add black borders
3. Fit the image into a square and use transparent borders (which would require PNG instead of JPG)

Considering that the thumbnails have a max size of 200px, option 3 seems best. The file sizes would continue to be quite small (70kb vs 9kb).

**Comment by javsezlol1** [comment]
ideally you would just render a square image for the sake of the thumbnail no ?. i think havving black bars or transparent borders will start to look messy

**Comment by ManOrMonster** [comment]
Yes, I started doing that once I noticed it resized them. Maybe a caption that explains that square images should be used.

**Comment by javsezlol1** [comment]
yea that sound like a good idea
